### PR TITLE
Support for ffmemless

### PR DESCRIPTION
**Pull request by taaem**
Update defines and conditionals to support ffmemless.

### CODE REVIEW

**Comment by taaem** [comment]
I tested it it pulls the right ffmemless if this line is present https://github.com/taaem/droid-hal-version-onyx/blob/master/rpm/droid-hal-version-onyx.spec#L10 and it should also work the other way around

**Comment by sledges** [comment]
Brilliant! Could you please write up a short tutorial (in piratepad) what else is needed to switch away from haptics-droid to a successful ffmemless implementation?
And if this package is the only thing that's needed in droid-hal-version, we can then merge this PR.

**Comment by taaem** [comment]
@sledges the qt5-feedback-haptics-ffmemless needs also to be build by build_packages.sh in droid-hal, to support that just add it or do i have to do some config magic there too?

**Comment by kimmoli** [comment]
It needs a kernel haptics driver that supports a memless interface (evdev). This is briefly explained in HADK pdf chapter 13.1.

Reference kernel driver implementation is here;
- https://github.com/kimmoli/android_kernel_oneplus_msm8974/pull/1

It needs also vibrator configuration files if defaults are not ok; (this was also in HADK)
- https://github.com/kimmoli/droid-config-onyx/commit/dac479716a6b4300be3c5875982265f6914bb498

And depends which evdev index the new ffmemless gets, one might need to change lipstick config;
- https://github.com/kimmoli/droid-config-onyx/pull/4/commits/73bb85fcdc5e2627a8cb0cea0fb5fc2ca9d8e814

**Comment by sledges** [comment]
Looks like we're done here then! Thanks!

**Comment by sledges** [comment]
@taaem, for now we just build only necessities in build_packages.sh (means no specific things like ffmemless).
Specialties are done via FAQ in piratepad, but in future all those (which won't catchup with next sfos releases) will need to be moved from there to HADK pdf, and hence build_packages.sh parametrised (or maybe that script could read droid-hal-version-$DEVICE.spec ? ;) )
ffmemless looks like a good training for such scenario :)

**Comment by taaem** [comment]
@sledges okay so thats of for later and we will just add it to the FAQ.
Maybe we could read the droid-hal-version-$DEVICE.spec, but technically even if it would build the then unnecessary other packages they wouldn't be picked up by mic, because they aren't in patterns so it wouldn't hurt anyone (except maybe the computer who builds it) to build all the packages in my opinion. One can always press no to jump one mw package.
But yes we also could implement some bash magic to parse some files, don't know what would be better tough :)

**Comment by kimmoli** [comment]
added info about memless to end of FAQ

**Pull request merged**
